# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
arr = np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [5]:
arr.shape

(39,)

5. Print the type of the previous array in question 3

In [6]:
type(arr)

numpy.ndarray

6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
# np.__config__.show()
np.show_config()

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Shaheen/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Shaheen/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Shaheen/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl

7. Print the dimension of the array in question 3


In [9]:
arr2 = np.array([1,2,3,4,5,6,7,8])
arr2
arr2.ndim

1

##### 8. Create a boolean array with all the True values

In [10]:
ar = np.ones(10, dtype = bool)
print(ar)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [16]:
arr2.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

10. Create a three dimensional array



In [17]:
arr2.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [23]:
arr2= arr2[::-1]
arr2

array([8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [3]:
null_vect = np.zeros(10)
null_vect[4]= 1
null_vect

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [31]:
identity = np.identity(3)
print(identity)
identity2= np.eye(3)
identity2

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [34]:
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3)
print(arr3.dtype)
arr3 = np.asfarray(arr3)
print(arr3)
arr3.dtype


[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]


dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [35]:
arr4 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr5 = np.array([[0., 4., 1.],[7., 2., 12.]])
multiply = arr4*arr5
multiply

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [40]:
arr6 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr7 = np.array([[0., 4., 1.],[7., 2., 12.]])
maxi = np.maximum(arr6,arr7)
maxi


array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [25]:
arr8 = np.arange(0,10)
print(arr8)
print(arr8[1::2])

odd=  [i for i in arr8 if i%2 == 1]
odd

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


[1, 3, 5, 7, 9]

18. Replace all odd numbers to -1 from previous array

In [26]:
arr8[1::2] = -1
arr8

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [76]:
arra = np.arange(10)
print(arra)
arra[5:-1:] = 12
arra

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [90]:
arra2 = np.ones(16)
x = arra2.reshape(4,4)
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [5]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1][1] = 12
# arr2d
# arr2d[1:,1:] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [99]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
arr3d[0] = 64
arr3d

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [7]:
arr_2d = np.arange(0,9).reshape(3,3)
print(arr_2d)
arr_2d[1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([3, 4, 5])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [10]:
arr_2d[1,1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [9]:
arr_2d = np.arange(0,9).reshape(3,3)
print(arr_2d)
arr_2d[:2,2:3]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
arr_random = np.random.randint(100, size=(10,10))
print(arr_random)


[[ 2 75  3 42  1 41 72 35  6 19]
 [ 3 70 52 90 32 81 70 39 89 98]
 [94 84 30 91 62 97 64  1 78 92]
 [72 33 25 59 15  6 40 81 54 52]
 [99 49 76 90 51 19  2 54 71 91]
 [81 41 48 21 42 39 32 27 28 59]
 [89 12 67 81 29 23 54 18 86 82]
 [62 79 83 78 90  0 82 67 99 39]
 [98 41 51  7 56 45 77 19 60 58]
 [65 14 98  1 27 33 84 81 39 68]]


In [35]:
print(np.min(arr_random))
np.max(arr_random)

0


99

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
# set(a) & set(b)
z = np.intersect1d(a,b)
z

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [4]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
# set(a)&set(b)
# print(np.intersect1d(a,b))
z = np.intersect1d(a,b)
for i in z:
    x = np.where(a == 4)
    y = np.where(a == 2)
print(y,x)

(array([1, 3], dtype=int64),) (array([5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'Will']

array([[ 0.69547068,  0.36219324,  1.0808765 ,  0.22402358],
       [-0.53692078,  0.31071628, -0.76210147,  0.40637575],
       [-0.76019226, -0.97905683, -0.82687166, -0.31131279],
       [-0.56859283,  0.39264165,  2.045161  ,  0.53087071],
       [-1.46610861,  0.41190971, -1.48858062, -1.78321936]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [8]:
print(data[names != 'Will'])
data[names != 'Joe']

[[ 0.69547068  0.36219324  1.0808765   0.22402358]
 [-0.53692078  0.31071628 -0.76210147  0.40637575]
 [-0.76019226 -0.97905683 -0.82687166 -0.31131279]
 [-0.56859283  0.39264165  2.045161    0.53087071]
 [-1.46610861  0.41190971 -1.48858062 -1.78321936]]


array([[ 0.69547068,  0.36219324,  1.0808765 ,  0.22402358],
       [ 0.37882554, -0.46794677, -0.52429998, -0.10684624],
       [-0.76019226, -0.97905683, -0.82687166, -0.31131279],
       [-0.18047157,  1.04574486,  1.05466164, -0.42338909]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [5]:
data = np.random.randn(1, 15).reshape(5,3)
data

array([[ 0.93943409, -0.32651408,  1.78673812],
       [ 1.65159089,  0.03369621,  0.14549942],
       [-0.24667755,  0.18016667,  0.13622277],
       [-0.02526865,  0.00496683,  0.00350596],
       [ 0.44123063,  1.42256488,  1.88978247]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [6]:
data = np.random.randn(1, 16).reshape(2,2,4)
data

array([[[-1.26064272,  1.4055582 ,  0.90601525,  1.21348247],
        [-1.08151846,  1.38892305, -1.24435712, -0.596668  ]],

       [[-0.55684476,  0.4796014 ,  0.96765124,  0.35788899],
        [-1.54250604,  0.35576943, -0.43279544,  1.05578602]]])

33. Swap axes of the array you created in Question 32

In [7]:
data = data.T
data

array([[[-1.26064272, -0.55684476],
        [-1.08151846, -1.54250604]],

       [[ 1.4055582 ,  0.4796014 ],
        [ 1.38892305,  0.35576943]],

       [[ 0.90601525,  0.96765124],
        [-1.24435712, -0.43279544]],

       [[ 1.21348247,  0.35788899],
        [-0.596668  ,  1.05578602]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [8]:
R = np.arange(10)
R = np.sqrt(R)
np.where(R<0.5, 0, R)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [38]:
A = np.random.randint(12)
R = np.random.randint(12)
np.maximum(A,R)

10

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
names = set(names)
# names.remove('Will')
names

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


{'Bob', 'Joe', 'Will'}

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [46]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a,b)
# print(set(a) or set(b))

# print(set(a) & set(b))
arr = np.concatenate((a, b))
arr = set(arr)
arr.remove(5)
arr

[1 2 3 4 5] [5 6 7 8 9]


{1, 2, 3, 4, 6, 7, 8, 9}

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [17]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
sampleArray[:3,1:2] = 10
sampleArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [4]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [9]:
matrix = np.random.randn(20)

In [10]:
matrix

array([-0.24530487,  0.72740672,  0.04959646, -0.01192869,  1.79661234,
        0.87104078,  1.04266398, -0.20926024,  1.93017235, -2.44346752,
       -0.5946943 ,  3.02971188,  1.60195587,  0.37803083,  1.51999495,
       -0.70148539, -1.77129776,  0.64598923, -0.64444657, -0.61489114])

In [11]:
matrix.cumsum()

array([-0.24530487,  0.48210185,  0.53169831,  0.51976962,  2.31638196,
        3.18742274,  4.23008672,  4.02082648,  5.95099882,  3.5075313 ,
        2.912837  ,  5.94254888,  7.54450475,  7.92253558,  9.44253054,
        8.74104515,  6.96974739,  7.61573661,  6.97129005,  6.35639891])