# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [4]:
arr = np.arange(0,10)
print(arr)
arr.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [5]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones(10,dtype = int).reshape(2,5)
print(arr1,arr2)
np.vstack((arr1,arr2))

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [11]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones(10,dtype = int).reshape(2,5)
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [13]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
print(arr)
arr.flatten()

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [23]:
arr = np.arange(15).reshape(1,3,5)
print(arr.ndim,"Dimension")
print(arr)
arr = arr.flatten()
print(arr.ndim,"Dimension")
arr

3 Dimension
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
1 Dimension


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [2]:
arr = np.arange(15).reshape(-1,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [9]:
arr = np.arange(30).reshape(5,6)
print(arr)
np.square(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529],
       [576, 625, 676, 729, 784, 841]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [11]:
np.random.seed(123)
arr = np.random.randint(60,size = (5,6))
arr.mean()

31.433333333333334

## Question:9

### Find the standard deviation of the previous array in Q8?

In [12]:
np.std(arr)

16.10938304908733

## Question:10

### Find the median of the previous array in Q8?

In [12]:
np.median(arr)

32.0

## Question:11

### Find the transpose of the previous array in Q8?

In [15]:
arr.T

array([[20, 17, 38, 38, 37],
       [59,  5, 37, 37,  8],
       [15, 19, 50, 25, 58],
       [36, 29, 53, 23, 40],
       [22, 54, 31, 33, 16],
       [45, 15, 10,  6, 42]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [16]:
arr = np.arange(16).reshape(4,4)
print(arr)
np.diagonal(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  5, 10, 15])

## Question:13

### Find the determinant of the previous array in Q12?

In [17]:
np.linalg.det(arr)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [18]:
arr = np.arange(15)
print(arr)
print(np.percentile(arr,5))
print(np.percentile(arr,95))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
0.7000000000000001
13.299999999999999


## Question:15

### How to find if a given array has any null values?

In [3]:
arr = np.array([1,2,4,np.nan,3,4])
print(arr)
np.isnan(arr)

[ 1.  2.  4. nan  3.  4.]


array([False, False, False,  True, False, False])